In [1]:
import pandas as pd

In [2]:
import sklearn as sk

In [290]:
# Load Data
data = pd.read_csv('project1_heart.csv', index_col = 0)
print(data)

     Age  Sex     ChestPain  RestBP   Chol  Fbs  RestECG  MaxHR  ExAng  \
1     63    1       typical   145.0  233.0    1        2  150.0      0
2     67    1  asymptomatic   160.0  286.0    0        2  108.0      1
3     67    1  asymptomatic   120.0  229.0    0        2  129.0      1
4     37    1    nonanginal   130.0  250.0    0        0  187.0      0
5     41    0    nontypical   130.0  204.0    0        2  172.0      0
..   ...  ...           ...     ...    ...  ...      ...    ...    ...
299   45    1       typical   110.0  264.0    0        0  132.0      0
300   68    1  asymptomatic   144.0  193.0    1        0  141.0      0
301   57    1  asymptomatic   130.0  131.0    0        0  115.0      1
302   57    0    nontypical   130.0  236.0    0        2  174.0      0
303   38    1    nonanginal   138.0  175.0    0        0  173.0      0

     Oldpeak  Slope   Ca        Thal  AHD
1        2.3      3  0.0       fixed   No
2        1.5      2  3.0      normal  Yes
3        2.6      2  2.0  reversable  Yes
4        3.5      3  0.0      normal   No
5        1.4      1  0.0      normal   No
..       ...    ...  ...         ...  ...
299      1.2      2  0.0  reversable  Yes
300      3.4      2  2.0  reversable  Yes
301      1.2      2  1.0  reversable  Yes
302      0.0      2  1.0      normal  Yes
303      0.0      1  NaN      normal   No

[303 rows x 14 columns]

In [291]:
# Data Summarization and Exploration

In [292]:
data.shape

(303, 14)

In [293]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 303 entries, 1 to 303
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        303 non-null    int64
 1   Sex        303 non-null    int64
 2   ChestPain  303 non-null    object
 3   RestBP     298 non-null    float64
 4   Chol       298 non-null    float64
 5   Fbs        303 non-null    int64
 6   RestECG    303 non-null    int64
 7   MaxHR      297 non-null    float64
 8   ExAng      303 non-null    int64
 9   Oldpeak    303 non-null    float64
 10  Slope      303 non-null    int64
 11  Ca         299 non-null    float64
 12  Thal       301 non-null    object
 13  AHD        303 non-null    object
dtypes: float64(5), int64(6), object(3)
memory usage: 35.5+ KB

In [294]:
data.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
1,63,1,typical,145.0,233.0,1,2,150.0,0,2.3,3,0.0,fixed,No
2,67,1,asymptomatic,160.0,286.0,0,2,108.0,1,1.5,2,3.0,normal,Yes
3,67,1,asymptomatic,120.0,229.0,0,2,129.0,1,2.6,2,2.0,reversable,Yes
4,37,1,nonanginal,130.0,250.0,0,0,187.0,0,3.5,3,0.0,normal,No
5,41,0,nontypical,130.0,204.0,0,2,172.0,0,1.4,1,0.0,normal,No

In [295]:
data.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       5
Chol         5
Fbs          0
RestECG      0
MaxHR        6
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [296]:
data.dropna()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
1,63,1,typical,145.0,233.0,1,2,150.0,0,2.3,3,0.0,fixed,No
2,67,1,asymptomatic,160.0,286.0,0,2,108.0,1,1.5,2,3.0,normal,Yes
3,67,1,asymptomatic,120.0,229.0,0,2,129.0,1,2.6,2,2.0,reversable,Yes
4,37,1,nonanginal,130.0,250.0,0,0,187.0,0,3.5,3,0.0,normal,No
5,41,0,nontypical,130.0,204.0,0,2,172.0,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,59,1,asymptomatic,164.0,176.0,1,2,90.0,0,1.0,2,2.0,fixed,Yes
299,45,1,typical,110.0,264.0,0,0,132.0,0,1.2,2,0.0,reversable,Yes
300,68,1,asymptomatic,144.0,193.0,1,0,141.0,0,3.4,2,2.0,reversable,Yes
301,57,1,asymptomatic,130.0,131.0,0,0,115.0,1,1.2,2,1.0,reversable,Yes
302,57,0,nontypical,130.0,236.0,0,2,174.0,0,0.0,2,1.0,normal,Yes

In [297]:
data.fillna(0)

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
1,63,1,typical,145.0,233.0,1,2,150.0,0,2.3,3,0.0,fixed,No
2,67,1,asymptomatic,160.0,286.0,0,2,108.0,1,1.5,2,3.0,normal,Yes
3,67,1,asymptomatic,120.0,229.0,0,2,129.0,1,2.6,2,2.0,reversable,Yes
4,37,1,nonanginal,130.0,250.0,0,0,187.0,0,3.5,3,0.0,normal,No
5,41,0,nontypical,130.0,204.0,0,2,172.0,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,45,1,typical,110.0,264.0,0,0,132.0,0,1.2,2,0.0,reversable,Yes
300,68,1,asymptomatic,144.0,193.0,1,0,141.0,0,3.4,2,2.0,reversable,Yes
301,57,1,asymptomatic,130.0,131.0,0,0,115.0,1,1.2,2,1.0,reversable,Yes
302,57,0,nontypical,130.0,236.0,0,2,174.0,0,0.0,2,1.0,normal,Yes
303,38,1,nonanginal,138.0,175.0,0,0,173.0,0,0.0,1,0.0,normal,No

In [298]:
new_df = data.fillna(0)
print(new_df)

     Age  Sex     ChestPain  RestBP   Chol  Fbs  RestECG  MaxHR  ExAng  \
1     63    1       typical   145.0  233.0    1        2  150.0      0
2     67    1  asymptomatic   160.0  286.0    0        2  108.0      1
3     67    1  asymptomatic   120.0  229.0    0        2  129.0      1
4     37    1    nonanginal   130.0  250.0    0        0  187.0      0
5     41    0    nontypical   130.0  204.0    0        2  172.0      0
..   ...  ...           ...     ...    ...  ...      ...    ...    ...
299   45    1       typical   110.0  264.0    0        0  132.0      0
300   68    1  asymptomatic   144.0  193.0    1        0  141.0      0
301   57    1  asymptomatic   130.0  131.0    0        0  115.0      1
302   57    0    nontypical   130.0  236.0    0        2  174.0      0
303   38    1    nonanginal   138.0  175.0    0        0  173.0      0

     Oldpeak  Slope   Ca        Thal  AHD
1        2.3      3  0.0       fixed   No
2        1.5      2  3.0      normal  Yes
3        2.6      2  2.0  reversable  Yes
4        3.5      3  0.0      normal   No
5        1.4      1  0.0      normal   No
..       ...    ...  ...         ...  ...
299      1.2      2  0.0  reversable  Yes
300      3.4      2  2.0  reversable  Yes
301      1.2      2  1.0  reversable  Yes
302      0.0      2  1.0      normal  Yes
303      0.0      1  0.0      normal   No

[303 rows x 14 columns]

In [299]:
new_df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           0
Thal         0
AHD          0
dtype: int64

In [300]:
#new_df.nunique()

In [301]:
hot = pd.get_dummies(new_df['ChestPain'], dtype = float)
hot1 = pd.get_dummies(new_df['RestECG'], dtype = float)
hot2 = pd.get_dummies(new_df['Slope'], dtype = float)
hot3 = pd.get_dummies(new_df['Ca'], dtype = float)
hot4 = pd.get_dummies(new_df['Thal'], dtype = float)

In [302]:
AHD = (new_df['AHD']).replace(['Yes','No'],['1','0']); AHD

1      0
2      1
3      1
4      0
5      0
      ..
299    1
300    1
301    1
302    1
303    0
Name: AHD, Length: 303, dtype: object

In [303]:
dat = new_df.drop(['ChestPain','RestECG', 'Slope', 'Ca','Thal', 'AHD'], axis = 1)
df = pd.concat([dat, hot, hot1, hot2, hot3, hot4, AHD], axis = 1)
df.head()

,Age,Sex,RestBP,Chol,Fbs,MaxHR,ExAng,Oldpeak,asymptomatic,nonanginal,...,3,0.0,1.0,2.0,3.0,0,fixed,normal,reversable,AHD
1,63,1,145.0,233.0,1,150.0,0,2.3,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0
2,67,1,160.0,286.0,0,108.0,1,1.5,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1
3,67,1,120.0,229.0,0,129.0,1,2.6,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1
4,37,1,130.0,250.0,0,187.0,0,3.5,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
5,41,0,130.0,204.0,0,172.0,0,1.4,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0

In [304]:
#df = pd.concat([new_df, hot, hot1, hot2, hot3, hot4, AHD_Yes], axis = 1)
#df.head()

In [305]:
print(df)

     Age  Sex  RestBP   Chol  Fbs  MaxHR  ExAng  Oldpeak  asymptomatic  \
1     63    1   145.0  233.0    1  150.0      0      2.3           0.0
2     67    1   160.0  286.0    0  108.0      1      1.5           1.0
3     67    1   120.0  229.0    0  129.0      1      2.6           1.0
4     37    1   130.0  250.0    0  187.0      0      3.5           0.0
5     41    0   130.0  204.0    0  172.0      0      1.4           0.0
..   ...  ...     ...    ...  ...    ...    ...      ...           ...
299   45    1   110.0  264.0    0  132.0      0      1.2           0.0
300   68    1   144.0  193.0    1  141.0      0      3.4           1.0
301   57    1   130.0  131.0    0  115.0      1      1.2           1.0
302   57    0   130.0  236.0    0  174.0      0      0.0           0.0
303   38    1   138.0  175.0    0  173.0      0      0.0           0.0

     nonanginal  ...    3  0.0  1.0  2.0  3.0    0  fixed  normal  reversable  \
1           0.0  ...  1.0  1.0  0.0  0.0  0.0  0.0    1.0     0.0         0.0
2           0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0    0.0     1.0         0.0
3           0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0    0.0     0.0         1.0
4           1.0  ...  1.0  1.0  0.0  0.0  0.0  0.0    0.0     1.0         0.0
5           0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0    0.0     1.0         0.0
..          ...  ...  ...  ...  ...  ...  ...  ...    ...     ...         ...
299         0.0  ...  0.0  1.0  0.0  0.0  0.0  0.0    0.0     0.0         1.0
300         0.0  ...  0.0  0.0  0.0  1.0  0.0  0.0    0.0     0.0         1.0
301         0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0    0.0     0.0         1.0
302         0.0  ...  0.0  0.0  1.0  0.0  0.0  0.0    0.0     1.0         0.0
303         1.0  ...  0.0  1.0  0.0  0.0  0.0  0.0    0.0     1.0         0.0

     AHD
1      0
2      1
3      1
4      0
5      0
..   ...
299    1
300    1
301    1
302    1
303    0

[303 rows x 27 columns]

In [306]:
from sklearn.model_selection import train_test_split

In [307]:
import numpy as np

In [309]:
n_class = len(np.unique(df['AHD'])) ; print(n_class)

2

In [311]:
np.unique(df['AHD'])

array(['0', '1'], dtype=object)

In [314]:
# Setting input features x and target output y
X = np.array(df.iloc[:,:-1]); print(X.shape)
y = np.array(df['AHD']); print(y.shape)
print(X.shape)
print(np.unique(y))
n_class = np.unique(y)

# Scaling
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)
x_scaled = scaler.transform(X)

# Split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
     x_scaled, y, test_size=0.33, random_state=4, stratify=y)

# Fit model
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(x_train, y_train)

# Evaluation --- Experiment 1
print('training performance: ', clf.score(x_train, y_train))
print('testing performance: ', clf.score(x_test, y_test))

(303, 26)
(303,)
(303, 26)
['0' '1']
training performance:  0.8620689655172413
testing performance:  0.88